config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get '/' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/expertise'=> 'static_pages#expertise'
  get '/itso-ipophl' => 'static_pages#itso_ipophl'
  get '/resources' => 'static_pages#resources'

  get '/contact' => 'static_pages#contact', as: 'contact'
  post '/contact' => 'static_pages#send_message_email'

  resources :users, except: [:new, :create]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :researchers

  resources :articles do
    collection do
      get 'tags/:tag', to: 'articles#index', as: :tag
    end
  end

  resources :ip_offers do
    collection do
      get '/tags/:tag', to: 'ip_offers#index', as: :tag
    end
  end

  resources :ip_needs do
    collection do
      get '/tags/:tag', to: 'ip_needs#index', as: :tag
    end
  end

  get '/tags' => 'tags#index'
  post '/subscribe' => 'subscriptions#subscribe'
  post '/unsubscribe' => 'subscriptions#unsubscribe'

  resources :industries do
    collection do
      get 'register' => 'industries#new'
    end
  end

  resources :academes do
    collection do
      get 'register' => 'academes#new'
    end
  end

  get '/admins' => 'admins#index'
  get '/admin' => 'admin_dashboards#analytics'
  get '/admin/manage_users' => 'admin_dashboards#manage_users'
  get '/admin/manage_ips' => 'admin_dashboards#manage_ips'
  get '/admin/manage_interactions' => 'admin_dashboards#manage_interactions'
  get '/admin/manage_articles' => 'admin_dashboards#manage_articles'
  get '/admin/manage_resources' => 'admin_dashboards#manage_resources'

  post '/admin/approve_ip' => 'admins#approve_ip'
  post '/admin/reject_ip' => 'admins#reject_ip'
  post '/admin/approve_user' => 'admins#approve_user'
  post '/admin/reject_user' => 'admins#reject_user'
  post '/admin/reactivate_user' => 'admins#reactivate_user'
  post '/admin/resend_activation_link' => 'admins#resend_activation_link'
  post '/admin/grant_admin_access' => 'admins#grant_admin_access'
  post '/admin/revoke_admin_access' => 'admins#revoke_admin_access'
  post '/admin/feature_article' => 'admins#feature_article'
  post '/admin/unfeature_article' => 'admins#unfeature_article'
  post '/admin/subfeature_article' => 'admins#subfeature_article'
  post '/admin/unsubfeature_article' => 'admins#unsubfeature_article'

  get '/dashboard' => 'user_dashboards#index', as: 'user_dashboard'
  get '/dashboard/tags/:tags', to: 'user_dashboards#index', as: :dashboard_tag
  get '/manage_submissions' => 'user_dashboards#manage_submissions'
  get '/manage_subscriptions' => 'user_dashboards#manage_subscriptions'
  get '/view_ips' => 'user_dashboards#view_ips'
end

app/models/ip_offer.rb
class IpOffer < ApplicationRecord
  include ApplicationHelper

  default_scope -> { order(created_at: :desc) }

  acts_as_taggable
  acts_as_taggable_on :tags

  acts_as_followable

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }

  belongs_to :user

  has_attached_file :photo, :styles => { :display => "200x106!"},
                    :url  => "/assets/ip-offers/:id/images/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/ip-offers/:id/images/:style/:basename.:extension"
  validates_attachment_size :photo, :less_than => 25.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :document, 
                    :url  => "/assets/ip-offers/:id/documents/:basename.:extension",
                    :path => ":rails_root/public/assets/ip-offers/:id/documents/:basename.:extension"
  validates_attachment_size :document, :less_than => 50.megabytes
  validates_attachment_content_type :document, :content_type => ['application/pdf', 'application/msword',
                           'application/vnd.openxmlformats-officedocument.wordprocessingml.document']

end

app/controllers/ip_offers_controller.rb
class IpOffersController < ApplicationController
  include ApplicationHelper

  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]  
  before_action :academe_or_admin_user, only: [:new, :create]
  
  def index
    if params[:tag]
      @ip_offers = IpOffer.tagged_with(params[:tag])
    else
      @ip_offers = IpOffer.all
    end
  end

  def show
    @ip = IpOffer.find(params[:id])
    @user = User.find(@ip.user_id)
  end

  def new
    @ip_offer = IpOffer.new
  end

  def create
    #render plain: params[:ip_offer].inspect
    @ip_offer = current_user.ip_offers.build(ip_offer_params)
    
    if @ip_offer.save
      @ip_offer.tag_list = params[:tag_list]
      flash[:success] = "Successfully created listing!"
      redirect_to @ip_offer
    else
      render 'new'
    end
  end

  def edit
    @ip_offer = IpOffer.find(params[:id])
  end

  def update
    @ip_offer = IpOffer.find(params[:id])
  
    if @ip_offer.update_attributes(ip_offer_params)
      flash[:success] = "Sucessfully updated listing!"
      redirect_to @ip_offer
    else
      render 'edit'
    end
  end

  def destroy
    @ip_offer = IpOffer.find(params[:id]).destroy
    flash[:success] = "Sucessfully deleted listing!"
    redirect_to ip_offers_path
  end

  private

    def ip_offer_params
      params.require(:ip_offer).permit(:title, :subtitle, :overview, :key_features,
                                       :applications, :customer_edge, :market_opportunity,
                                       :patent_status, :photo, :document, :tag_list)
    end

    def correct_user
      @ip_offer = IpOffer.find(params[:id])
      @user = User.find(@ip_offer.user_id)
      redirect_to(root_path) unless current_user?(@user)
    end    

end

app/helpers/ip_offers_helper.rb
module IpOffersHelper
  include ActsAsTaggableOn::TagsHelper
  
  def selPatentStatus
    @patent_status = ['Filed','Patented'] 
  end

  def selCategory
    @categories = ['Trademark', 'Copyright']
  end

end

app/views/ip_offers/_ip_offer_form.html.slim
= form_for @ip_offer, html: {class: 'ui form'} do |f|
  = render 'shared/error_messages', object: f.object

  .field.required
    = f.label :title, 'Short Title', class: 'required'
    = f.text_field :title, class: 'form-control'

  .field
    = f.label :subtitle, 'Long Title'
    = f.text_area :subtitle, class: 'form-control'
  
  .field.required
    = f.label :overview, 'Overview', class: 'required'
    = f.text_area :overview, class: 'form-control'

  .field
    = f.label :key_features, 'Key Features'
    = f.text_area :key_features, class: 'form-control'

  .field
    = f.label :applications, 'Applications'
    = f.text_area :applications, class: 'form-control'

  .field
    = f.label :customer_edge, 'Customer Edge'
    = f.text_area :customer_edge, class: 'form-control'

  .field
    = f.label :market_opportunity, 'Market Opportunity'
    = f.text_area :market_opportunity, class: 'form-control'

  .field
    = f.label :photo, 'Photo Attachment'
    = f.file_field :photo, class: 'form-control'

  .field
    = f.label :document, 'Document Attachment'
    = f.file_field :document, class: 'form-control'

  .field
    = f.label :patent_status, 'Patent Status'
    = f.select(:patent_status, selPatentStatus, {prompt: 'Select Patent Status'}, class: 'form-control')

  .field
    = f.label :tags
    = f.text_field :tag_list, class: 'form-control'

  .field
    = f.submit yield(:button_text), class: "ui button primary"

app/views/ip_offers/_sidebar.html.slim
.six.wide.column
  .ui.sticky style="z-index: 1;"
    .ui.segment
      .ui.search
        .ui.icon.input style="width: 100%;"
          input.prompt type="text" placeholder="Search"
          i.search.icon
        .results
      - if current_user && current_user.accounts.class != Industry          
        br
          = link_to 'Submit New Offer', new_ip_offer_path, class: 'ui button primary fluid'
    .ui.segment
      h2.ui.header style="background-color: #888; text-align: center;"
        = @ip.title
      .ui.image
        - if @ip.photo.present?
          = image_tag @ip.photo.url, style: "width: 400px; height: 200px;"
        - else
          = image_tag 'placeholders/no_image_general.jpg', style: "width: 400px; height: 200px;"
      - if current_user
        br
        br
        - if current_user.id != @ip.user_id
         - if !current_user.following?(@ip)
           = render 'subscribe'
         - else
           = render 'unsubscribe'
        - if @ip.document.present?
          br
            = link_to 'Download PDF Copy', @ip.document.url(:original, false), class: 'ui button positive fluid'
      - if current_user == @user || (current_user && current_user.admin?)
        br
        .ui.buttons.fluid
          = link_to 'Edit', edit_ip_offer_path(@ip), class: 'ui button orange'
          = link_to 'Delete', ip_offer_path(@ip.id), method: :delete, data: {:confirm => 'Are you sure?'}, class: 'ui button red'
      br
      br
      | Tags: 
      = raw @ip.tag_list.map { |t| link_to t, tag_ip_offers_path(t)}.join(', ')

app/views/ip_offers/_subscribe.html.slim
= form_tag('/subscribe', id:'subscription_form', method: 'subscribe') do
  = hidden_field_tag :authenticity_token, form_authenticity_token
  = hidden_field_tag :follower_id, current_user.id
  = hidden_field_tag :followed_id, @ip.id
  = hidden_field_tag :followed_type, @ip.class
  = submit_tag 'Subscribe', class: 'ui button primary fluid'

app/views/ip_offers/_unsubscribe.html.slim
= form_tag('/unsubscribe', id: 'subscription_form', method: 'unsubscribe') do
  = hidden_field_tag :authenticity_token, form_authenticity_token
  = hidden_field_tag :follower_id, current_user.id
  = hidden_field_tag :followed_id, @ip.id
  = hidden_field_tag :followed_type, @ip.class
  = submit_tag 'Unsubscribe', class: 'ui button primary fluid'

app/views/ip_offers/edit.html.slim
- provide(:title, 'Edit IP Offer')
- provide(:button_text, 'Save Changes') 
.container-fluid
  h1
    | Edit IP Offer

  .row
    .col-md-6.col-md-offset-3
      = render 'ip_offer_form'

app/views/ip_offers/index.html.slim
.ui.container style="margin-top: 100px;"
  h2.ui.header.center.aligned IP Offers Listing
  .ui.search style="margin-bottom: 20px;"
      .ui.icon.input style="width: 100%;"
        input.prompt type="text" placeholder="Search"
        i.search.icon
      .results
  .ui.grid
    - @ip_offers.each do |ip_offer|
      .row.ui.basic.segment
        .five.wide.column
          .ui.image.left.floated.middle.aligned.medium
            - if ip_offer.photo.present?
              = image_tag ip_offer.photo.url, style: "width: 250px; height: 200px;"
            - else
              = image_tag 'placeholders/no_image_general.jpg', style: "width: 250px; height: 200px;"
        .eleven.wide.column
          h3.ui.header 
            .content
              = link_to ip_offer.title, ip_offer
            .sub.header
              | Posted by 
              = fullname(User.find(ip_offer.user_id)) + ' | '
              = local_time(ip_offer.created_at)
          p 
            = simple_format(truncate(ip_offer.overview, length: 500))
            | Tags: 
            = raw ip_offer.tag_list.map { |t| link_to t, tag_ip_offers_path(t)}.join(', ')

app/views/ip_offers/new.html.slim
- provide(:title, 'New IP Offer')
- provide(:button_text, 'Submit IP Offer')

.ui.grid
  .column.centered style="padding-top: 20px;"
    h1.ui.header.center.aligned Submit IP Offer
    .ui.divider
    .ui.segment
      = render 'ip_offer_form'

app/views/ip_offers/show.html.slim
/= social_share_button_tag(@ip.title)

.ui.grid.container
  .row style="margin-top: 100px;"
    .ten.wide.column
      h2.ui.header 
        .content 
          - if !@ip.subtitle.nil? && !@ip.subtitle.empty?
            = @ip.subtitle
          - else
            = @ip.title
          .sub.header = @ip.inventors if !@ip.inventors.nil? && !@ip.inventors.empty?
      .ui.divider
      - if !@ip.overview.nil? && !@ip.overview.empty?      
        h3.ui.header
          | Overview:
        p 
          = simple_format(@ip.overview)
        .ui.divider
      - if current_user
        - if !@ip.key_features.nil? && !@ip.key_features.empty?
          h3.ui.header
            | Key Features:
          p 
            = simple_format(@ip.key_features)
          .ui.divider
        - if !@ip.applications.nil? && !@ip.applications.empty? 
          h3.ui.header
            | Applications:
          p 
            = simple_format(@ip.applications)
          .ui.divider
        - if !@ip.customer_edge.nil? && !@ip.customer_edge.empty?
          h3.ui.header
            | Customer Edge:
          p 
            = simple_format(@ip.customer_edge)
          .ui.divider
        - if !@ip.market_opportunity.nil? && !@ip.market_opportunity.empty?
          h3.ui.header
            | Market Opportunity:
          p 
            = simple_format(@ip.market_opportunity)
      - else
        | You have limited access to view the whole page. Sign up as 
        = link_to ' academe user ', register_academes_path
        | or as
        = link_to ' industry user ', register_industries_path
        | and
        = link_to ' login ', login_path
        | to view full page
        .ui.divider
    = render 'sidebar'