config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get '/' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/expertise'=> 'static_pages#expertise'
  get '/itso-ipophl' => 'static_pages#itso_ipophl'
  get '/resources' => 'static_pages#resources'

  get '/contact' => 'static_pages#contact', as: 'contact'
  post '/contact' => 'static_pages#send_message_email'

  resources :users, except: [:new, :create]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :researchers

  resources :articles do
    collection do
      get 'tags/:tag', to: 'articles#index', as: :tag
    end
  end

  resources :ip_offers do
    collection do
      get '/tags/:tag', to: 'ip_offers#index', as: :tag
    end
  end

  resources :ip_needs do
    collection do
      get '/tags/:tag', to: 'ip_needs#index', as: :tag
    end
  end

  get '/tags' => 'tags#index'
  post '/subscribe' => 'subscriptions#subscribe'
  post '/unsubscribe' => 'subscriptions#unsubscribe'

  resources :industries do
    collection do
      get 'register' => 'industries#new'
    end
  end

  resources :academes do
    collection do
      get 'register' => 'academes#new'
    end
  end

  get '/admins' => 'admins#index'
  get '/admin' => 'admin_dashboards#analytics'
  get '/admin/manage_users' => 'admin_dashboards#manage_users'
  get '/admin/manage_ips' => 'admin_dashboards#manage_ips'
  get '/admin/manage_interactions' => 'admin_dashboards#manage_interactions'
  get '/admin/manage_articles' => 'admin_dashboards#manage_articles'
  get '/admin/manage_resources' => 'admin_dashboards#manage_resources'

  post '/admin/approve_ip' => 'admins#approve_ip'
  post '/admin/reject_ip' => 'admins#reject_ip'
  post '/admin/approve_user' => 'admins#approve_user'
  post '/admin/reject_user' => 'admins#reject_user'
  post '/admin/reactivate_user' => 'admins#reactivate_user'
  post '/admin/resend_activation_link' => 'admins#resend_activation_link'
  post '/admin/grant_admin_access' => 'admins#grant_admin_access'
  post '/admin/revoke_admin_access' => 'admins#revoke_admin_access'
  post '/admin/feature_article' => 'admins#feature_article'
  post '/admin/unfeature_article' => 'admins#unfeature_article'
  post '/admin/subfeature_article' => 'admins#subfeature_article'
  post '/admin/unsubfeature_article' => 'admins#unsubfeature_article'

  get '/dashboard' => 'user_dashboards#index', as: 'user_dashboard'
  get '/dashboard/tags/:tags', to: 'user_dashboards#index', as: :dashboard_tag
  get '/manage_submissions' => 'user_dashboards#manage_submissions'
  get '/manage_subscriptions' => 'user_dashboards#manage_subscriptions'
  get '/view_ips' => 'user_dashboards#view_ips'
end

app/controllers/admin_dashboards_controller.rb
class AdminDashboardsController < ApplicationController
  include ApplicationHelper
  
  before_action :logged_in_user
  before_action :admin_user

  def analytics
  end

  def manage_users
    @users = User.all
    @approved_users = User.where(approval_status: 'approved', activated: true).where.not(activated_at: nil)
    @pending_activation_users = User.where(activated: false, activated_at: nil)
    @pending_approval_users = User.where(approval_status: 'pending')
    @deactivated_users = User.where(approval_status: 'approved', activated: false).where.not(activated_at: nil)
    @rejected_users = User.where(approval_status: 'rejected')

    @admin_users = User.where(admin: true)
    @approved_admin_users = User.where(admin: true, approval_status: 'approved', activated: true).where.not(activated_at: nil)
    @pending_activation_admin_users = User.where(admin: true, activated: false, activated_at: nil)
    @pending_approval_admin_users = User.where(admin: true, approval_status: 'pending')
    @deactivated_admin_users = User.where(admin: true, approval_status: 'approved', activated: false).where.not(activated_at: nil)
    @rejected_admin_users = User.where(admin: true, approval_status: 'rejected')

    @academe_users = User.where(accounts_type: "Academe", admin: false, )
    @approved_academe_users = User.where(accounts_type: "Academe", admin: false, approval_status: 'approved', activated: true).where.not(activated_at: nil)
    @pending_activation_academe_users = User.where(accounts_type: "Academe", admin: false, activated: false, activated_at: nil)
    @pending_approval_academe_users = User.where(accounts_type: "Academe", admin: false, approval_status: 'pending')
    @deactivated_academe_users = User.where(accounts_type: "Academe", admin: false, approval_status: 'approved', activated: false).where.not(activated_at: nil)
    @rejected_academe_users = User.where(accounts_type: "Academe", admin: false, approval_status: 'rejected')

    @industry_users = User.where(accounts_type: "Industry", admin: false,)
    @approved_industry_users = User.where(accounts_type: "Industry", admin: false, approval_status: 'approved', activated: true).where.not(activated_at: nil)
    @pending_activation_industry_users = User.where(accounts_type: "Industry", admin: false, activated: false, activated_at: nil)
    @pending_approval_industry_users = User.where(accounts_type: "Industry", approval_status: 'pending')
    @deactivated_industry_users = User.where(accounts_type: "Industry", admin: false, approval_status: 'approved', activated: false).where.not(activated_at: nil)
    @rejected_industry_users = User.where(accounts_type: "Industry", admin: false, approval_status: 'rejected')
  end

  def manage_ips
    # Load Offers
    @offers = IpOffer.all
    @accepted_offers = IpOffer.where(approval_status: 'approved')
    @pending_offers = IpOffer.where(approval_status: 'pending')
    @rejected_offers = IpOffer.where(approval_status: 'rejected')
    # Load Needs
    @needs = IpNeed.all
    @accepted_needs = IpNeed.where(approval_status: 'approved')
    @pending_needs = IpNeed.where(approval_status: 'pending')
    @rejected_needs = IpNeed.where(approval_status: 'rejected')
    # Load All
    @ips = (@offers + @needs)
    @accepted_ips = (@accepted_offers + @accepted_needs)
    @pending_ips = (@pending_offers + @pending_needs)
    @rejected_ips = (@rejected_offers + @rejected_needs)
  end

  def manage_interactions
    @all_follows = Follow.all
  end

  def manage_articles
    @featured_article = Article.where(featured: true).first
    @subfeatured_articles = SubfeaturedArticle.all.order(ranking: :asc)
    @articles = Article.all
  end

  def manage_resources
  end

end

app/helpers/admin_dashboards_helper.rb
module AdminDashboardsHelper
end

app/views/admin_dashboards/analytics.html.slim
div style="padding-right: 14px;"
  h1.ui.header Website Analytics
  .ui.divider

app/views/admin_dashboards/manage_articles.html.slim
div style="padding-right: 14px;"
  h1.ui.header Manage Articles
  .ui.divider

#admin-manage-articles
  .ui.secondary.menu
    a.item.active data-tab="all-articles"  Overview 
  .ui.tab.segment.active data-tab="all-articles"  
    .ui.top.attached.tabular.menu
      a.item.active data-tab="all-articles/featured"  Featured
      a.item data-tab="all-articles/all"  All
    .ui.bottom.attached.tab.segment.active data-tab="all-articles/featured"
      h3.ui.header.center.aligned Main Featured Article
      table.ui.celled.table
        thead
          tr
            th.center.aligned ID
            th.center.aligned Title
            th.center.aligned Actions
        tbody        
          tr
            - if @featured_article
              td.center.aligned
                = @featured_article.id
              td
                = link_to @featured_article.title, @featured_article
              td.center.aligned
                = link_to 'Unfeature', admin_unfeature_article_path(id: @featured_article), method: :post, data: {:confirm => 'Do you want to unfeature this article?'}, class: 'compact ui button orange mini'
                = link_to 'Edit', edit_article_path(@featured_article), class: 'compact ui button primary mini'
                = link_to 'Delete', article_path(@featured_article), method: :delete, data: {:confirm => 'Are you sure?'}, class: 'compact ui button red mini'
            - else
              td.center.aligned colspan="3"
                | Nothing to display
        tfoot
          tr.center.aligned
            th colspan="3"
      .ui.divider
      h3.ui.header.center.aligned Sub-Featured Articles
      table.ui.celled.table
        thead
          tr
            th.center.aligned Rank
            th.center.aligned ID
            th.center.aligned Title
            th.center.aligned Actions
        tbody
          - if !@subfeatured_articles.empty?
            - @subfeatured_articles.each_with_index do |a, i|       
              - article = Article.find(a.article_id)    
              tr
                td.center.aligned
                  = a.ranking
                td.center.aligned
                  = article.id
                td
                  = link_to article.title, article
                td.center.aligned
                  = link_to 'Unsubfeature', admin_unsubfeature_article_path(id: a.id), method: :post, data: {:confirm => 'Do you really want to remove this article from the subfeatured articles?'}, class: 'compact ui button orange mini'
                  = link_to 'Edit', edit_article_path(article), class: 'compact ui button primary mini'
                  = link_to 'Delete', article_path(article), method: :delete, data: {:confirm => 'Do you really want to delete this article?'}, class: 'compact ui button red mini'
          - else
            tr
              td.center.aligned colspan="4"
                | Nothing to display
        tfoot
          tr.center.aligned
            th colspan="4"
      .ui.divider 
    .ui.bottom.attached.tab.segment data-tab="all-articles/all"
      table#all-articles-data-table.ui.celled.table[width="100%" cellspacing="0"]
        thead
          tr
            th.center.aligned ID
            th.center.aligned Title
            th.center.aligned Tags
            th.center.aligned Actions
        tbody
          - @articles.each_with_index do |article, i|           
            tr
              td.center.aligned
                = article.id
              td
                - if article.featured
                  .ui.teal.horizontal.label.tiny Featured
                - if subfeatured?(article)
                  .ui.olive.horizontal.label.tiny Subfeatured                
                = link_to article.title, article            
              td.center.aligned
                - if article.tagged_with?('announcement')
                  .ui.tag.label.mini.red announcement
                - if article.tagged_with?('news')
                  .ui.tag.label.mini.green news                
                - if article.tagged_with?('feature')
                  .ui.tag.label.mini.purple feature
              td.center.aligned
                - if !article.featured
                  = link_to 'Feature', admin_feature_article_path(id: article), method: :post, data: {:confirm => 'Featuring this article will remove the current featured article. Do you want to proceed?'}, class: 'compact ui button green mini'
                - else
                  = link_to 'Unfeature', admin_unfeature_article_path(id: article), method: :post, data: {:confirm => 'Do you want to unfeature this article?'}, class: 'compact ui button orange mini'
                = link_to 'Edit', edit_article_path(article), class: 'compact ui button primary mini'
                = link_to 'Delete', article_path(article), method: :delete, data: {:confirm => 'Are you sure?'}, class: 'compact ui button red mini'
        tfoot
          tr.center.aligned
            th colspan="4"
              i.fa.fa-file-text-o
              = " #{@articles.count} Articles | "
              i.fa.fa-newspaper-o
              = " #{@articles.tagged_with('news').count} News | "
              i.fa.fa-star
              = " #{@articles.tagged_with('feature').count} Features | "
              i.fa.fa-bullhorn
              = " #{@articles.tagged_with('announcement').count} Announcments"
    h2.ui.header Article Settings
    .ui.divider
    br
    .ui.container.grid.stackable
      .row
        .four.wide.column
          .row
            .ui.top.left.attached.green.label Add Subfeatured Article
        .twelve.wide.column
          .ui.form
            = form_tag('/admin/subfeature_article', id:'admin_subfeature_article', method: 'subfeature_article') do
              .inline.fields
                .two.wide.field
                  = label_tag :ranking, "Ranking: "
                .two.wide.field
                  = select_tag(:ranking, options_for_select([1, 2, 3, 4]))
                .two.wide.field
                  = label_tag :article_id, "Select Article: "
                .six.wide.field
                  = select_tag(:article_id, options_from_collection_for_select(Article.all, 'id', 'title'), prompt: 'Select Article')
                .four.wide.field
                  = submit_tag "Subfeature Article", class: 'ui right floated button primary'

app/views/admin_dashboards/manage_interactions.html.slim
div style="padding-right: 14px;"
  h1.ui.header Manage Interactions
  .ui.divider

table#manage-all-user-ip-interaction-data-table.ui.celled.table[width="100%" cellspacing="0"]
  thead
    tr
      th.center.aligned IP Type
      th.center.aligned IP Title
      th.center.aligned Submitted By
      th.center.aligned Interested Party
  tbody
    - @all_follows.each_with_index do |follow, i|
      - ip = get_ip(follow.followable_type, follow.followable_id)
      - poster = ip_poster(ip)
      - interested = User.find(follow.follower_id)  
      tr
        td.center.aligned
          = ip_type(ip)
        td
          = link_to ip.title, ip
        td
          = link_to poster.email, poster
        td
          = link_to interested.email, interested
  tfoot
    tr.center.aligned
      th colspan="4"

app/views/admin_dashboards/manage_resources.html.slim
div style="padding-right: 14px;"
  h1.ui.header Manage Resources
  .ui.divider