config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get '/' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/expertise'=> 'static_pages#expertise'
  get '/itso-ipophl' => 'static_pages#itso_ipophl'
  get '/resources' => 'static_pages#resources'

  get '/contact' => 'static_pages#contact', as: 'contact'
  post '/contact' => 'static_pages#send_message_email'

  resources :users, except: [:new, :create]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :researchers

  resources :articles do
    collection do
      get 'tags/:tag', to: 'articles#index', as: :tag
    end
  end

  resources :ip_offers do
    collection do
      get '/tags/:tag', to: 'ip_offers#index', as: :tag
    end
  end

  resources :ip_needs do
    collection do
      get '/tags/:tag', to: 'ip_needs#index', as: :tag
    end
  end

  get '/tags' => 'tags#index'
  post '/subscribe' => 'subscriptions#subscribe'
  post '/unsubscribe' => 'subscriptions#unsubscribe'

  resources :industries do
    collection do
      get 'register' => 'industries#new'
    end
  end

  resources :academes do
    collection do
      get 'register' => 'academes#new'
    end
  end

  get '/admins' => 'admins#index'
  get '/admin' => 'admin_dashboards#analytics'
  get '/admin/manage_users' => 'admin_dashboards#manage_users'
  get '/admin/manage_ips' => 'admin_dashboards#manage_ips'
  get '/admin/manage_interactions' => 'admin_dashboards#manage_interactions'
  get '/admin/manage_articles' => 'admin_dashboards#manage_articles'
  get '/admin/manage_resources' => 'admin_dashboards#manage_resources'

  post '/admin/approve_ip' => 'admins#approve_ip'
  post '/admin/reject_ip' => 'admins#reject_ip'
  post '/admin/approve_user' => 'admins#approve_user'
  post '/admin/reject_user' => 'admins#reject_user'
  post '/admin/reactivate_user' => 'admins#reactivate_user'
  post '/admin/resend_activation_link' => 'admins#resend_activation_link'
  post '/admin/grant_admin_access' => 'admins#grant_admin_access'
  post '/admin/revoke_admin_access' => 'admins#revoke_admin_access'
  post '/admin/feature_article' => 'admins#feature_article'
  post '/admin/unfeature_article' => 'admins#unfeature_article'
  post '/admin/subfeature_article' => 'admins#subfeature_article'
  post '/admin/unsubfeature_article' => 'admins#unsubfeature_article'

  get '/dashboard' => 'user_dashboards#index', as: 'user_dashboard'
  get '/dashboard/tags/:tags', to: 'user_dashboards#index', as: :dashboard_tag
  get '/manage_submissions' => 'user_dashboards#manage_submissions'
  get '/manage_subscriptions' => 'user_dashboards#manage_subscriptions'
  get '/view_ips' => 'user_dashboards#view_ips'
end

app/models/ip_need.rb
class IpNeed < ApplicationRecord
  include ApplicationHelper
  
  default_scope -> { order(created_at: :desc) }

  acts_as_taggable
  acts_as_taggable_on :tags

  acts_as_followable

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true

  belongs_to :user

  has_attached_file :photo, :styles => { :display => "200x106!"},
                    :url  => "/assets/ip-needs/:id/images/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/ip-needs/:id/images/:style/:basename.:extension"
  validates_attachment_size :photo, :less_than => 25.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  has_attached_file :document, 
                    :url  => "/assets/ip-needs/:id/documents/:basename.:extension",
                    :path => ":rails_root/public/assets/ip-needs/:id/documents/:basename.:extension"
  validates_attachment_size :document, :less_than => 50.megabytes
  validates_attachment_content_type :document, :content_type => ['application/pdf', 'application/msword',
                           'application/vnd.openxmlformats-officedocument.wordprocessingml.document']

end

app/controllers/ip_needs_controller.rb
class IpNeedsController < ApplicationController
  include ApplicationHelper

  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]  

  def index
    if params[:tag]
      @ip_needs = IpNeed.tagged_with(params[:tag])
    else
      @ip_needs = IpNeed.all
    end
  end

  def show
    @ip = IpNeed.find(params[:id])
    @user = User.find(@ip.user_id)
  end

  def new
    @ip_need = IpNeed.new
  end

  def create
    #render plain: params[:ip_need].inspect
    @ip_need = current_user.ip_needs.build(ip_need_params)

    if @ip_need.save
      flash[:success] = "Successfully created listing!"
      redirect_to @ip_need
    else
      render 'new'
    end    
  end

  def edit
    @ip_need = IpNeed.find(params[:id])
  end

  def update
    @ip_need = IpNeed.find(params[:id])
  
    if @ip_need.update_attributes(ip_need_params)
      flash[:success] = "Sucessfully updated listing!"
      redirect_to @ip_need
    else
      render 'edit'
    end    
  end

  def destroy
    @ip_need = IpNeed.find(params[:id]).destroy
    flash[:success] = "Succesfully deleted listing!"
    redirect_to ip_needs_path
  end

  private

    def ip_need_params
      params.require(:ip_need).permit(:title, :description, :features, :business_model,
                                      :privacy_option, :photo, :document, :tag_list)
    end

    def correct_user
      @ip_need = IpNeed.find(params[:id])
      @user = User.find(@ip_need.user_id)
      redirect_to(root_path) unless current_user?(@user)
    end 
end

app/helpers/ip_needs_helper.rb
module IpNeedsHelper
  include ActsAsTaggableOn::TagsHelper

  def selPrivacyOptions
    @patent_status = ['Private', 'Public'] 
  end

end

app/views/ip_needs/_ip_need_form.html.slim
= form_for @ip_need, html: {class: 'ui form'} do |f|
  = render 'shared/error_messages', object: f.object

  .field.required
    = f.label :title, 'Title', class: 'required'
    = f.text_field :title, class: 'form-control'
  
  .field.required
    = f.label :description, 'Description', class: 'required'
    = f.text_area :description, class: 'form-control'

  .field
    = f.label :features, 'Features'
    = f.text_area :features, class: 'form-control'

  .field
    = f.label :business_model, 'Business Model'
    = f.text_area :business_model, class: 'form-control'

  .field
    = f.label :photo, 'Photo Attachment'
    = f.file_field :photo, class: 'form-control'

  .field
    = f.label :document, 'Document Attachment'
    = f.file_field :document, class: 'form-control'

  .field
    = f.label :privacy_option, "Privacy Option", class: 'required'
    = f.select(:privacy_option, selPrivacyOptions, {prompt: 'Select Privacy Option'}, class: 'form-control')

  .field
    = f.label :tags
    = f.text_field :tag_list, class: 'form-control'
 
  .field
    = f.submit yield(:button_text), class: "ui button primary"

app/views/ip_needs/_sidebar.html.slim
.six.wide.column
  .ui.sticky style="z-index: 1;"
    .ui.segment
      .ui.search
        .ui.icon.input style="width: 100%;"
          input.prompt type="text" placeholder="Search"
          i.search.icon
        .results
      - if current_user          
        br
          = link_to 'Submit New Need', new_ip_offer_path, class: 'ui button primary fluid'
    .ui.segment
      h2.ui.header style="background-color: #888; text-align: center;"
        = @ip.title
      .ui.image
        - if @ip.photo.present?
          = image_tag @ip.photo.url, style: "width: 400px; height: 200px;"
        - else
          = image_tag 'placeholders/no_image_general.jpg', style: "width: 400px; height: 200px;"
      - if current_user
        br
        br
        - if current_user.id != @ip.user_id
         - if !current_user.following?(@ip)
           = render 'subscribe'
         - else
           = render 'unsubscribe'
        - if @ip.document.present?
          br
            = link_to 'Download PDF Copy', @ip.document.url(:original, false), class: 'ui button positive fluid'
      - if current_user == @user || (current_user && current_user.admin?)
        br
        .ui.buttons.fluid
          = link_to 'Edit', edit_ip_offer_path(@ip), class: 'ui button orange'
          = link_to 'Delete', ip_offer_path(@ip.id), method: :delete, data: {:confirm => 'Are you sure?'}, class: 'ui button red'
      br
      br
      | Tags: 
      = raw @ip.tag_list.map { |t| link_to t, tag_ip_needs_path(t)}.join(', ')

app/views/ip_needs/_subscribe.html.slim
= form_tag('/subscribe', id:'subscription_form', method: 'subscribe') do
  = hidden_field_tag :authenticity_token, form_authenticity_token
  = hidden_field_tag :follower_id, current_user.id
  = hidden_field_tag :followed_id, @ip.id
  = hidden_field_tag :followed_type, @ip.class
  = submit_tag "Subscribe", class: 'ui button primary fluid'

app/views/ip_needs/_unsubscribe.html.slim
= form_tag('/unsubscribe', id: 'subscription_form', method: 'unsubscribe') do
  = hidden_field_tag :authenticity_token, form_authenticity_token
  = hidden_field_tag :follower_id, current_user.id
  = hidden_field_tag :followed_id, @ip.id
  = hidden_field_tag :followed_type, @ip.class
  = submit_tag "Unsubscribe", class: 'ui button primary fluid'

app/views/ip_needs/edit.html.slim
- provide(:title, 'Edit IP Need')
- provide(:button_text, 'Save Changes') 

h1
  | Edit IP Need

.row
  .col-md-6.col-md-offset-3
    = render 'ip_need_form'

app/views/ip_needs/index.html.slim
.ui.container style="margin-top: 100px;"
  h2.ui.header.center.aligned IP Needs Listing
  .ui.search style="margin-bottom: 20px;"
      .ui.icon.input style="width: 100%;"
        input.prompt type="text" placeholder="Search"
        i.search.icon
      .results
  .ui.grid
    - @ip_needs.each do |ip_need|
      .row.ui.basic.segment
        .five.wide.column
          .ui.image.left.floated.middle.aligned.medium
            - if ip_need.photo.present?
              = image_tag ip_need.photo.url, style: "width: 250px; height: 200px;"
            - else
              = image_tag 'placeholders/no_image_general.jpg', style: "width: 250px; height: 200px;"
        .eleven.wide.column  
          h3.ui.header 
            .content
              = link_to ip_need.title, ip_need
            .sub.header
              | Posted by 
              = fullname(User.find(ip_need.user_id)) + ' | '
              = local_time(ip_need.created_at)
          p 
            = simple_format(truncate(ip_need.description, length: 500))
            | Tags: 
            = raw ip_need.tag_list.map { |t| link_to t, tag_ip_needs_path(t)}.join(', ')

app/views/ip_needs/new.html.slim
- provide(:title, 'New IP Need')
- provide(:button_text, 'Create')

.ui.grid
  .column.centered style="padding-top: 20px;"
    h1.ui.header.center.aligned Submit IP Need
    .ui.divider
    .ui.segment
      = render 'ip_need_form'

app/views/ip_needs/show.html.slim
/= social_share_button_tag(@ip.title)

.ui.grid.container
  .row style="margin-top: 100px;"
    .ten.wide.column
      h2.ui.header 
        .content 
          = @ip.title
      .ui.divider
      - if !@ip.description.nil? && !@ip.description.empty?      
        h3.ui.header
          | Description:
        p 
          = simple_format(@ip.description)
        .ui.divider
      - if current_user
        - if !@ip.features.nil? && !@ip.features.empty?
          h3.ui.header
            | Features:
          p 
            = simple_format(@ip.features)
          .ui.divider
        - if !@ip.business_model.nil? && !@ip.business_model.empty? 
          h3.ui.header
            | Business Model:
          p 
            = simple_format(@ip.business_model)
          .ui.divider
      - else
        | You have limited access to view the whole page. Sign up as 
        = link_to ' academe user ', register_academes_path
        | or as
        = link_to ' industry user ', register_industries_path
        | and
        = link_to ' login ', login_path
        | to view full page
        .ui.divider
    = render 'sidebar'