config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  get '/' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/expertise'=> 'static_pages#expertise'
  get '/itso-ipophl' => 'static_pages#itso_ipophl'
  get '/resources' => 'static_pages#resources'

  get '/contact' => 'static_pages#contact', as: 'contact'
  post '/contact' => 'static_pages#send_message_email'

  resources :users, except: [:new, :create]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :researchers

  resources :articles do
    collection do
      get 'tags/:tag', to: 'articles#index', as: :tag
    end
  end

  resources :ip_offers do
    collection do
      get '/tags/:tag', to: 'ip_offers#index', as: :tag
    end
  end

  resources :ip_needs do
    collection do
      get '/tags/:tag', to: 'ip_needs#index', as: :tag
    end
  end

  get '/tags' => 'tags#index'
  post '/subscribe' => 'subscriptions#subscribe'
  post '/unsubscribe' => 'subscriptions#unsubscribe'

  resources :industries do
    collection do
      get 'register' => 'industries#new'
    end
  end

  resources :academes do
    collection do
      get 'register' => 'academes#new'
    end
  end

  get '/admins' => 'admins#index'
  get '/admin' => 'admin_dashboards#analytics'
  get '/admin/manage_users' => 'admin_dashboards#manage_users'
  get '/admin/manage_ips' => 'admin_dashboards#manage_ips'
  get '/admin/manage_interactions' => 'admin_dashboards#manage_interactions'
  get '/admin/manage_articles' => 'admin_dashboards#manage_articles'
  get '/admin/manage_resources' => 'admin_dashboards#manage_resources'

  post '/admin/approve_ip' => 'admins#approve_ip'
  post '/admin/reject_ip' => 'admins#reject_ip'
  post '/admin/approve_user' => 'admins#approve_user'
  post '/admin/reject_user' => 'admins#reject_user'
  post '/admin/reactivate_user' => 'admins#reactivate_user'
  post '/admin/resend_activation_link' => 'admins#resend_activation_link'
  post '/admin/grant_admin_access' => 'admins#grant_admin_access'
  post '/admin/revoke_admin_access' => 'admins#revoke_admin_access'
  post '/admin/feature_article' => 'admins#feature_article'
  post '/admin/unfeature_article' => 'admins#unfeature_article'
  post '/admin/subfeature_article' => 'admins#subfeature_article'
  post '/admin/unsubfeature_article' => 'admins#unsubfeature_article'

  get '/dashboard' => 'user_dashboards#index', as: 'user_dashboard'
  get '/dashboard/tags/:tags', to: 'user_dashboards#index', as: :dashboard_tag
  get '/manage_submissions' => 'user_dashboards#manage_submissions'
  get '/manage_subscriptions' => 'user_dashboards#manage_subscriptions'
  get '/view_ips' => 'user_dashboards#view_ips'
end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.3.7"
  end

end

app/views/layouts/_footer.html.slim
.ui.divider
footer
  .ui.grid.container.stackable
    .two.column.row
      .column
        h3
          |  Contact Us
        p
          i.fa.fa-building.fa-fw
          |  Lower Ground Floor, PHIVOLCS Bldg., C.P. Garcia Avenue, Diliman, Quezon City, Philippines 
          br
          i.fa.fa-facebook-official.fa-fw
          a [href="https://www.facebook.com/IPtechtransfer.upd/"]  UP Diliman IP & Technology Transfer
          br
          i.fa.fa-envelope.fa-fw
          |  techtransfer.ovcrd@up.edu.ph
          br
          i.fa.fa-phone.fa-fw
          |  (02) 981 8763
      .column
        h3
          | Quick Links
        p
          a [href="http://info.ipophil.gov.ph/itso/"] Innovation and Technology Support Offices (ITSO)
          br
          a [href="http://www.ipophil.gov.ph/"] Intellectual Property Office of the Philippines (IPOPHL)
          br
          a [href="http://www.ovcrd.upd.edu.ph/"] Office of the Vice Chancellor for Research and Development (OVCRD)
          br
          a [href="http://upd.edu.ph/"] University of the Philippines Diliman (UPD)
          br
          a [href="http://www.dost.gov.ph/"] Department of Science and Technology (DOST)
          br
  .row.footer-below
    p
      | Copyright © 2017 Intellectual Property and Technology Transfer Unit, OVCRD, University of the Philippines Diliman 

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "UP IPTTU", root_path, id: "logo"
    nav
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "Home", root_path
        li
          = link_to "About Us", about_path
        li
          = link_to "Expertise", expertise_path
        li
          = link_to "Opportunities", opportunities_path
        li
          = link_to "ITSO-IPOPHL", itso_ipophl_path
        li
          = link_to "Resources", resources_path
        - if logged_in?
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#"
              | Account
              span.caret
            ul.dropdown-menu role="menu"
              li
                = link_to "Profile", current_user
              li
                = link_to "Settings", edit_user_path(current_user)
              li.divider
              li
                = link_to "Logout", logout_path, method: "delete"
        - else
          li
            = link_to "Log in", login_path
          li
            = link_to "Register", register_path

app/views/layouts/_navbar.html.slim
.ui.borderless.fixed.menu
  .ui.container
    = link_to  image_tag("logo/navbar-banner.png", size: "200x50", class: "ui image"), root_path, class: 'header item'
    = link_to 'Home', root_path, class: 'item'
    = link_to 'About', about_path, class: 'item'

    .ui.dropdown.item 
      | IP Portal &nbsp;
      .i.fa.fa-caret-down
      .menu
        = link_to 'Offers', ip_offers_path, class: 'item'
        = link_to 'Needs', ip_needs_path, class: 'item'

    = link_to 'Articles', articles_path, class: 'item'
    
    /= link_to 'Expertise', expertise_path, class: 'item'
    
    = link_to 'ITSO-IPOPHL', itso_ipophl_path, class: 'item'

    = link_to 'Resources', resources_path, class: 'item'

    = link_to 'Contact', contact_path, class: 'item'
    .right.menu
      - if !current_user
        = link_to 'Login', login_path, class: 'item'
        .ui.dropdown.item 
          | Register &nbsp;
          .i.fa.fa-caret-down
          .menu
            = link_to 'Academe', register_academes_path, class: 'item'
            = link_to 'Industry', register_industries_path, class: 'item'
      - else
        a.item
          = link_to 'Profile', current_user, class: 'item'
        a.item
          = link_to 'Logout', logout_path, method: 'delete', class: 'item'

app/views/layouts/_rails_default.html.slim
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': false
= javascript_include_tag 'application', 'data-turbolinks-track': false

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.slim
.ui.grid
  .row
    .two.wide.column style="height: 100%;"
      .ui.vertical.menu style="border: none; width:100%"
        a.item href="/"
          = image_tag("logo/sidebar-banner.png", class: "ui image small")
        .item 
          .header Main
          .menu
            = link_to 'Home', root_path, class: 'item'
            = link_to 'Profile', current_user, class: 'item'
            = link_to 'Contact', contact_path, class: 'item' if !current_user.admin?
            = link_to 'Logout', logout_path, method: 'delete', class: 'item'
        - if current_user.admin?
          .item 
            .header Users
            .menu
              = link_to 'Manage Users', admin_manage_users_path, class: 'item'
        .item
          .header IP Portal
          .menu
            - if current_user.admin?
              = link_to 'Manage IPs', admin_manage_ips_path, class: 'item'
              = link_to 'Manage Interactions', admin_manage_interactions_path, class: 'item'
              = link_to 'Submit New Offer', new_ip_offer_path, class: 'item'
              = link_to 'Submit New Need', new_ip_need_path, class: 'item'
            - else
              = link_to 'Manage Submissions', manage_submissions_path, class: 'item'
              = link_to 'Manage Subscriptions', manage_subscriptions_path, class: 'item'
              = link_to 'View All IPs', view_ips_path, class: 'item'
              - if current_user.admin? || academe_user?
                = link_to 'Submit New Offer', new_ip_offer_path, class: 'item'
              = link_to 'Submit New Need', new_ip_need_path, class: 'item'              
        .item  
          .header Article
          .menu
            - if current_user.admin?
              = link_to 'Manage Articles', admin_manage_articles_path, class: 'item'
              = link_to 'Post New Article', new_article_path, class: 'item'
            - else
              = link_to 'View Articles', articles_path, class: 'item'
        .item  
          .header Resources
          .menu
            - if current_user.admin?
              = link_to 'Manage Resources', admin_manage_resources_path, class: 'item'
              a.item Upload New Resource
            - else
              = link_to 'View Resources', resources_path, class: 'item'
    .thirteen.wide.column style="padding-top: 30px;"
      /= render 'shared/flash'
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = render 'layouts/rails_default'
    = render 'layouts/shim'
    = favicon_link_tag 'favicon.ico'
  
  body
    .wrapper
      - if !current_user
        = render 'layouts/navbar'
        /= render 'shared/flash'
        = yield
      - else
        = render 'layouts/sidebar'

      = render 'layouts/footer'
    
    javascript:
      $('.ui.checkbox').checkbox();
      $('.ui.dropdown').dropdown();
      $('.ui.sticky').sticky({
        offset: 60
      });
      $('#admin-manage-ip .menu .item').tab({
        context: $('#admin-manage-ip')
      });
      $('#admin-manage-users .menu .item').tab({
        context: $('#admin-manage-users')
      });
      $('#admin-manage-articles .menu .item').tab({
        context: $('#admin-manage-articles')
      });